export enum CARequestStatusEnum {
  REQUESTED = 'REQUESTED',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum CAApprovalStatusEnum {
  REQUESTED = 'REQUESTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  NO_APPROVAL = 'NO_APPROVAL',
  PASSED = 'PASSED',
}

export enum CAWorkflowTypeEnum {
  CA_WORKFLOW_APPROVER = 'CA_WORKFLOW_APPROVER',
  CA_WORKFLOW_READER = 'CA_WORKFLOW_READER',
  CA_WORKFLOW_CHECKER = 'CA_WORKFLOW_CHECKER',
}
