export enum LBApprovalStatusEnum {
  REQUESTED = 'REQUESTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  NO_APPROVAL = 'NO_APPROVAL',
  PASSED = 'PASSED',
}

export enum LBWorkflowTypeEnum {
  LB_WORKFLOW_APPROVER = 'LB_WORKFLOW_APPROVER',
  LB_WORKFLOW_READER = 'LB_WORKFLOW_READER',
  LB_WORKFLOW_CHECKER = 'LB_WORKFLOW_CHECKER',
}
