export enum LearningCalendarType {
  ASSIGNED_LEARNING = 'ASSIGNED_LEARNING',
  LEARNING = 'LEARNING',
  AVAILABLE_LEARNING = 'AVAILABLE_LEARNING',
  SHARING_KNOWLEDGE = 'SHARING_KNOWLEDGE',
  SURVEY = 'SURVEY',
  EVALUATION = 'EVALUATION',
}

export enum StatusCalender {
  AVAILABLE = 'AVAILABLE',
  PLOTTED = 'PLOTTED',
  REQUESTED = 'REQUESTED',
  SCHEDULED = 'SCHEDULED',
  FULL_BOOKED = 'FULL_BOOKED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
}
