export enum PerformanceOtherEnum {
  TYPE = 'type',
  ORGANIZER = 'organizer',
  METHOD = 'method',
  VENUE = 'venue',
}

export enum PerformanceStatusEnum {
  DRAFT = 'DRAFT',
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PFWorkflowTypeEnum {
  PF_WORKFLOW_APPROVER = 'PF_WORKFLOW_APPROVER',
  PF_WORKFLOW_READER = 'PF_WORKFLOW_READER',
  NULL = 'NULL',
}

export enum FinalResultMethodEnum {
  SINGLE = 'SINGLE',
  MULTIPLE = 'MULTIPLE',
}

export enum FormMemberEnum {
  EMPLOYEE = 'EMPLOYEE',
  POSITION = 'POSITION',
}

export enum FormTermEnum {
  MID_END_YEAR = 'MID_END_YEAR',
  END_YEAR = 'END_YEAR',
}

export enum timelineEnum {
  GOAL_SETTING_SELF = 'GOAL_SETTING_SELF',
  GOAL_SETTING_DIRECT_MANAGER = 'GOAL_SETTING_DIRECT_MANAGER',
  GOAL_SETTING_ABOVE_DIRECT_MANAGER = 'GOAL_SETTING_ABOVE_DIRECT_MANAGER',
  MID_YEAR_COACHING_SELF = 'MID_YEAR_COACHING_SELF',
  MID_YEAR_COACHING_DIRECT_MANAGER = 'MID_YEAR_COACHING_DIRECT_MANAGER',
  MID_YEAR_COACHING_ABOVE_DIRECT_MANAGER = 'MID_YEAR_COACHING_ABOVE_DIRECT_MANAGER',
  END_YEAR_APPRAISEE = 'END_YEAR_APPRAISEE',
  END_YEAR_DIRECT_MANAGER = 'END_YEAR_DIRECT_MANAGER',
  END_YEAR_ABOVE_DIRECT_MANAGER = 'END_YEAR_ABOVE_DIRECT_MANAGER',
  PERFORMANCE_APPRAISAL_COMPLETED = 'PERFORMANCE_APPRAISAL_COMPLETED',
}

export enum GetDataTimelineControlEnum {
  SELECTED_TRUE = 'SELECTED_TRUE',
}

export enum PerfSuperiorStatusEnum {
  PENDING = 'PENDING',
  REQUESTED = 'REQUESTED',
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  REVISED = 'REVISED',
  PASSED = 'PASSED',
  NO_APPROVAL = 'NO_APPROVAL',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}
