export enum ReportProgressTypeDataEnum {
  XLSX = 'XLSX',
  PDF = 'PDF',
}

export enum ReportProgressTypeEnum {
  HUMAN_ASSET_VALUE = 'HUMAN_ASSET_VALUE',
  FLIGHT_RISK = 'FLIGHT_RISK',
  TALENT_DEMOGRAPHY = 'TALENT_DEMOGRAPHY',
  TALENT_PRO_READINESS = 'TALENT_PRO_READINESS',
  TALENT_TURN_OVER_RATE = 'TALENT_TURN_OVER_RATE',
  LEADERSHIP_ASSESSMENT = 'LEADERSHIP_ASSESSMENT',
  IDP_PROGRESS_REPORT = 'IDP_PROGRESS_REPORT',
  IDP_PROGRESS_SUMMARY = 'IDP_PROGRESS_SUMMARY',
  SUCCESS_PROFILE_EMP = 'SUCCESS_PROFILE_EMP',
  SUCCESS_PROFILE_POS = 'SUCCESS_PROFILE_POS',
  LNA_SKILL = 'LNA_SKILL',
  LNA_LEARNING = 'LNA_LEARNING',
  LEARNING_MASTER_DATA = 'LEARNING_MASTER_DATA',
  LEARNING_BUDGET_EMP = 'LEARNING_BUDGET_EMP',
  LEARNING_BUDGET_GROUP = 'LEARNING_BUDGET_GROUP',
  LEARNING_SLOT = 'LEARNING_SLOT',
  LEARNING_BUDGET_APPROVAL = 'LEARNING_BUDGET_APPROVAL',
  LEARNING_KNOWLEDGE_SHARING = 'LEARNING_KNOWLEDGE_SHARING',
  LEARNING_PLOT = 'LEARNING_PLOT',
  LEARNING_BUDGET_APPROVAL_DETAIL = 'LEARNING_BUDGET_APPROVAL_DETAIL',
  LEARNING_EVALUATION = 'LEARNING_EVALUATION',
  LEARNING_RECORD = 'LEARNING_RECORD',
  PERF_MONITORING = 'PERF_MONITORING',
  PERF_APPROVER_PA = 'PERF_APPROVER_PA',
  PERF_KPI_SCORE = 'PERF_KPI_SCORE',
  PERF_FINAL_EVAL = 'PERF_FINAL_EVAL',
  PA_FORM_BY_EMP = 'PA_FORM_BY_EMP',
  LEARNING_REQUEST = 'LEARNING_REQUEST',
  LEARNING_SESSION = 'LEARNING_SESSION',
  IDP_LIST_APPROVER = 'IDP_LIST_APPROVER',
}

export enum ReportProgressStatusEnum {
  PROCESSING = 'PROCESSING',
  FINISHED = 'FINISHED',
  STOPPED = 'STOPPED',
}
