export enum SchedulerEnum {
  PRACTICAL_EXPERIENCE_SCHEDULER = 'Practical-Experience-Scheduler',
  IDP_REMINDER = 'IDP_REMINDER',
  LEARNING_CALENDER = 'LEARNING_CALENDER',
  LEARNING_EVAL_REMINDER = 'LEARNING_EVAL_REMINDER',
  LEARNING_EVAL_PARTICIPANT_REMINDER = 'LEARNING_EVAL_PARTICIPANT_REMINDER',
  LEARNING_REALIZATION_REMINDER = 'LEARNING_REALIZATION_REMINDER',
  SUCESS_PROFILE_REMINDER = 'Success-Profile-Reminder',
  JOB_NAME_SUNFISH_DATA_FEEDING = 'SUNFISH_SYNCHRONIZATION',
  LOGIN_AUDIT_SYNC_SCHEDULER = 'LOGIN_AUDIT_SYNC_SCHEDULER',
  ACTIVITY_LOG_SYNC_SCHEDULER = 'ACTIVITY_LOG_SYNC_SCHEDULER',
}

export enum SchedulerOptionEnum {
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
  YEARLY = 'YEARLY',
}

export enum SchedulerDaysEnum {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
}

export enum SchedulerMonthsEnum {
  JANUARY = 1,
  FEBRUARY = 2,
  MARCH = 3,
  APRIL = 4,
  MAY = 5,
  JUNE = 6,
  JULY = 7,
  AUGUST = 8,
  SEPTEMBER = 9,
  OCTOBER = 10,
  NOVEMBER = 11,
  DECEMBER = 12,
}
