export enum PerfEmployeeStatusEnum {
  AVAILABLE = 'AVAILABLE',
  DRAFT = 'DRAFT',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REVISED = 'REVISED',
  APPROVED = 'APPROVED',
  NO_APPROVAL = 'NO_APPROVAL',
  EXPIRED = 'EXPIRED',
}
